### ISSUE TITLE
 有内存泄露的问题

### ISSUE THREAD

**Issue by vbgood-cloud** [warrially/BaziGo#2]
代码如下
func bz(t time.Time) string {
	pBazi := bazi.GetBazi(t.Year(), int(t.Month()), t.Day(), t.Hour(), t.Minute(), t.Second(), 0)
	sz := pBazi.SiZhu()
	s := sz.YearZhu().GanZhi().ToString() + sz.MonthZhu().GanZhi().ToString() + sz.DayZhu().GanZhi().ToString() + sz.HourZhu().GanZhi().ToString()
	return s
}

	begin := time.Date(1931, 9, 18, 0, 0, 0, 0, time.Local)
	end := time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local)

	for t := begin; end.After(t); t = t.AddDate(0, 1, 0) {
		println(t.Format("2006-01-02 15:04:05"), bz(t))
	}

出现如下错误
PS D:\lab\go\bazi> go run .\main.go
1931-09-18 00:00:00
1931-09-18 00:00:00 辛未丁酉丙子戊子
1931-10-18 00:00:00 辛未戊戌丙午戊子
1931-11-18 00:00:00 辛未己亥丁丑庚子
1931-12-18 00:00:00 辛未庚子丁未庚子
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xac8caa]

goroutine 1 [running]:
github.com/warrially/BaziGo.(*TLunarDate).GetAllDays(...)
        d:/dev/gopath/pkg/mod/github.com/warrially/!bazi!go@v1.0.1/lunardate.go:851
github.com/warrially/BaziGo.(*TLunarDate).Get64TimeStamp(...)
        d:/dev/gopath/pkg/mod/github.com/warrially/!bazi!go@v1.0.1/lunardate.go:335
github.com/warrially/BaziGo.(*TLunarDate).GetMonthFrom64TimeStamp(0xc000052050, 0xe30318100)
        d:/dev/gopath/pkg/mod/github.com/warrially/!bazi!go@v1.0.1/lunardate.go:306 +0xaa
github.com/warrially/BaziGo.NewLunarDateFrom64TimeStamp(0xe30318100, 0xe30318100)
        d:/dev/gopath/pkg/mod/github.com/warrially/!bazi!go@v1.0.1/lunardate.go:60 +0x6d
github.com/warrially/BaziGo.(*TSolarDate).ToLunarDate(0xc000050a50, 0xfe7540)
        d:/dev/gopath/pkg/mod/github.com/warrially/!bazi!go@v1.0.1/solardate.go:328 +0x45
github.com/warrially/BaziGo.(*TBazi).init(0xc00001a780, 0xc00001a780)
        d:/dev/gopath/pkg/mod/github.com/warrially/!bazi!go@v1.0.1/bazi.go:59 +0x2b5
github.com/warrially/BaziGo.NewBazi(...)
        d:/dev/gopath/pkg/mod/github.com/warrially/!bazi!go@v1.0.1/bazi.go:12
github.com/warrially/BaziGo.GetBazi(0x78c, 0x1, 0x12, 0x0, 0x0, 0x0, 0x0, 0x11)
        d:/dev/gopath/pkg/mod/github.com/warrially/!bazi!go@v1.0.1/bazi.go:33 +0xb2
main.bz(0x0, 0xe302d1c00, 0xfe6c00, 0xb2de88, 0x13)
        D:/lab/go/bazi/main.go:19 +0x26d
main.main()
        D:/lab/go/bazi/main.go:57 +0x205
exit status 2

**Comment by warrially** [comment]
已经修复了。 多谢提醒
