### ISSUE TITLE
报告一个bug，输入2020-01-01会崩溃

### ISSUE THREAD

**Issue by chadwi** [warrially/BaziGo#3]
lunardate.go

159 行  if m.nLeapMonth == 0 {
		// 没有闰月的话 nMonth 只能是 1 ~ 12
		if m.nMonth == 13 {
			return false  **// 输入 2020-01-01 会走到这里！**
		}
	}

**Comment by chadwi** [comment]
还有一个问题 hour 输入一个大值，也会崩溃，没有做边界约束

**Comment by warrially** [comment]
> lunardate.go
> 
> 159 行 if m.nLeapMonth == 0 { // 没有闰月的话 nMonth 只能是 1 ~ 12 if m.nMonth == 13 { return false **// 输入 2020-01-01 会走到这里！** } }

是的， 这是一个重大的bug, 已修复

**Comment by warrially** [comment]
> 还有一个问题 hour 输入一个大值，也会崩溃，没有做边界约束

已经做了限制， 谢谢

**Comment by wtyqwer** [comment]
good
